

import Head from 'next/head'
import Image from 'next/image'
import BarChart from '../../components/BarChart';
import LineChart from '../../components/LineChart';
import LineC from '../../components/LineChart';


import Header from '../../components/Header';
import Recents from '../../components/Recents';
import TopCards from '../../components/TopCards';
import Donut from '../../components/DonutPM25';
import Googlemap from '../../components/Googlemap';

export default function Maps() {
  return (
    <>
      <Head>
        <title>IoT Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-gray-100 min-h-screen px-20'>
        <div className='pb-6'>
        <Header />

        </div>
        
        <Googlemap />
        
      </main>
      </>
      );
  }
